import localFont from "next/font/local";
import "@/styles/globals.scss";
import SideNav from "@/components/SideNav";
import { ThemeProvider } from "@context/ThemeContext";
import Gutter from "@components/gutter";
import TopNav from "@components/TopNav";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.cdnfonts.com/css/kimberly-signature" rel="stylesheet" />
                
      </head>
      <body>
        {/* <Gutter> */}
      <ThemeProvider>
        <TopNav/>
        <SideNav/>

        {children}
        </ThemeProvider>
        {/* </Gutter> */}
      </body>
    </html>
  );
}
